version: '3.9'

services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
  
  mysql:
    image: mysql
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: test-jobseeker
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "3306:3306"
